import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'projectOverview',
      items: [
        'OVERVIEW',
        'PRINCIPLES',
        'ROADMAP',
      ],
    },
    {
      type: 'category',
      label: 'architecture',
      items: [
        'ARCHITECTURE',
        'INFRA_DEPLOYMENT',
      ],
    },
    {
      type: 'category',
      label: '도구',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tools',
        },
      ],
    },
  ],
};

export default sidebars;