import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'project-overview',
      link: {
        type: 'generated-index',
        title: '프로젝트 개요 문서'
      },
      items: [
        'project-overview/OVERVIEW',
        'project-overview/PRINCIPLES',
        'project-overview/ROADMAP',
        'project-overview/architecture/ARCHITECTURE',
        'project-overview/infra-deployment/INFRA_DEPLOYMENT',
      ],
    },
    {
      type: 'category',
      label: 'tools',
      link: {
        type: 'generated-index',
        title: '도구 문서'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tools',
        },
      ],
    },
    {
      type: 'link',
      label: 'SurfAI',
      href: 'https://surfai.org',
    },
  ],
};

export default sidebars;