import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: '프로젝트 개요',
      items: [
        'OVERVIEW',
        'PRINCIPLES',
        'ROADMAP',
        'DECISION_LOG',
      ],
    },
    {
      type: 'category',
      label: '아키텍처',
      items: [
        'ARCHITECTURE',
        'INFRA_DEPLOYMENT',
      ],
    },
    {
      type: 'category',
      label: '백엔드',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend',
        },
      ],
    },
    {
      type: 'category',
      label: '프론트엔드',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend',
        },
      ],
    },
  ],
};

export default sidebars;